name: funground_client_web
description: An absolute bare-bones web app.
# version: 1.0.0
#homepage: https://www.example.com
#author: Your Name <email@example.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
#  path: ^1.4.1
  react: ^4.6.1
  http: ^0.11.3
  funground_client_lib:
    path: ../funground_client_lib

dev_dependencies:
  build_runner: ^1.1.2
  build_web_compilers: ^1.0.0
  pedantic: ^1.0.0
